chore: add Cognito auth configuration
epam/ai-dial pull request #96
Opened 2024-04-22 09:50 UTC by alexey-ban

2024-04-22 10:05 UTC, alexey-ban commented on docs/tutorials/cognito-quick-start.md
> +      ```https://cognito-idp.{region}.amazonaws.com/{my-pool-id}```
In one place, <> is used for meta replacement, and in another - {}. We should adopt a unified style.

2024-04-22 10:05 UTC, alexey-ban commented on docs/tutorials/cognito-quick-start.md
> +
Add intro

2024-04-23 09:48 UTC, sr-remsha requested changes
@alexey-ban please review changes

2024-04-23 15:41 UTC, sr-remsha approved these changes

2024-04-23 15:43 UTC, merged